"""Deterministic anti-slop + structure lint for HTML/CSS design artifacts.

Rules mirror skills/hermes-design-verify/references/lint-rules.md
L3 in the verify stack — no model calls.
"""

from __future__ import annotations

import re
from pathlib import Path

from drafthouse.models import LintIssue, LintResult

# (rule_id, severity, pattern, message)
_RULES: list[tuple[str, str, re.Pattern[str], str]] = [
    (
        "purple-gradient",
        "P0",
        re.compile(
            r"(purple|violet|indigo)[^\n]{0,40}(gradient)|linear-gradient\([^)]*(#7c3aed|#8b5cf6|#6d28d9|#a855f7)",
            re.I,
        ),
        "Aggressive purple/violet gradient — classic AI-slop tell.",
    ),
    (
        "ai-default-indigo",
        "P0",
        re.compile(r"#6366f1|#4f46e5|#4338ca", re.I),
        "Default AI indigo/violet brand hex without design-system justification.",
    ),
    (
        "emoji-feature-icons",
        "P0",
        re.compile(
            "[\U0001F300-\U0001FAFF☀-➿✨🚀🎯💡🔥⚡🎉]"
        ),
        "Generic emoji used as feature icons — replace with brand marks or omit.",
    ),
    (
        "invented-metric",
        "P0",
        re.compile(
            r"\b\d+\s*[×x]\s*faster\b|\b99\.9\s*%\s*uptime\b|\b10\s*[×x]\s*productivity\b|"
            r"\bworld[- ]class\b|\bnext[- ]generation\b|\bunlock\s+(your|the)\b",
            re.I,
        ),
        "Invented or unsourced marketing metric / filler claim.",
    ),
    (
        "filler-copy",
        "P0",
        re.compile(
            r"\bFeature\s+(One|Two|Three|Four)\b|\bLorem ipsum\b|\bYour text here\b|"
            r"\bComing soon\b.{0,20}$|\bTBD\b",
            re.I | re.M,
        ),
        "Placeholder or filler copy shipped as content.",
    ),
    (
        "display-ui-default-font",
        "P1",
        re.compile(
            r"font-family\s*:[^;{]*(?:Inter|Roboto|Arial|Helvetica)[^;{]*;",
            re.I,
        ),
        "Inter/Roboto/Arial/Helvetica declared as a display family (body use is fine — check context).",
    ),
    (
        "gradient-on-every-bg",
        "P1",
        re.compile(r"linear-gradient\(", re.I),
        "Gradient present — ensure it is not applied to every section background.",
    ),
    (
        "left-border-card-cliche",
        "P1",
        re.compile(
            r"border-left\s*:\s*(?:4|5|6)px\s+solid[^;]+;[\s\S]{0,200}border-radius\s*:\s*(?:1[0-9]|[89])px",
            re.I,
        ),
        "Rounded card + thick left accent cliché — prefer layout hierarchy over default cards.",
    ),
    (
        "icon-every-heading",
        "P1",
        re.compile(r"<h[1-6][^>]*>[\s\S]{0,80}?(?:<svg|<i |<img|✨|🚀)", re.I),
        "Heading appears to carry an icon — only if the brand system requires it.",
    ),
    (
        "warm-ai-beige-bg",
        "P1",
        re.compile(
            r"(background(?:-color)?\s*:[^;{]*(?:#f5f0e8|#f4f1ea|#faf6f0|#f8f4ec|#e8dcc8)|"
            r"oklch\(\s*0\.9[0-9]\s+0\.0[1-9]\s+[2-9][0-9])",
            re.I,
        ),
        "Warm beige/cream page background — allowed only if brand/direction requires it.",
    ),
    (
        "designer-chrome-leak",
        "P0",
        re.compile(
            r"\b(Viewport|Breakpoint|Design Mode|Token Inspector|Demo Controls|"
            r"Figma Export|AI Generated by)\b",
            re.I,
        ),
        "Designer/demo chrome exposed as product UI.",
    ),
    (
        "orphan-br",
        "P2",
        re.compile(r"<br\s*/?>\s*<br\s*/?>\s*<br\s*/?>", re.I),
        "Stacked <br> — use spacing scale / margins instead.",
    ),
]


def _line_of(text: str, index: int) -> int:
    return text.count("\n", 0, index) + 1


def lint_text(text: str, path: str = "<memory>") -> LintResult:
    result = LintResult(path=path)
    lower_findings: set[str] = set()

    for rule_id, severity, pattern, message in _RULES:
        for match in pattern.finditer(text):
            # de-dupe emoji rule noise slightly
            key = f"{rule_id}:{match.start() // 80}"
            if key in lower_findings:
                continue
            lower_findings.add(key)
            start = max(0, match.start() - 20)
            excerpt = text[start : match.end() + 20].replace("\n", " ")[:80]
            result.issues.append(
                LintIssue(
                    rule_id=rule_id,
                    severity=severity,
                    message=message,
                    line=_line_of(text, match.start()),
                    excerpt=excerpt,
                )
            )
            # one hit per rule is enough for P0 messaging
            if severity == "P0":
                break
    return result


def lint_file(path: str | Path) -> LintResult:
    p = Path(path)
    if not p.exists():
        return LintResult(
            path=str(p),
            issues=[
                LintIssue(
                    rule_id="file-missing",
                    severity="P0",
                    message=f"File not found: {p}",
                )
            ],
        )
    text = p.read_text(encoding="utf-8", errors="replace")
    return lint_text(text, path=str(p))
